### ISSUE TITLE
how to get the y distributions values

### ISSUE THREAD

**Issue by nicmazza** [jdhuang-csm/bayes-drt2#1]
Hi ! 

First of all, I want to thank you for this, and especially for converting it to cmdstan which made installation sooooo much easier!
I would like to ask how to access the y values that are plotted via _inv_DRT.plot_distribution_  and store them in an array or something similar. 
My question might be a bit basic as I am still a beginner. I would like to get the data to do some basic rule of thumb estimation, since the peak fitting function while very convenient struggles a bit with my datasets. I tried looking into the functions but I could not find a way. 

Best

**Comment by jdhuang-csm** [comment]
Hello, and thanks for the kind feedback!

`drt.predict_distribution(tau)` will return an array of DRT values at the points specified in the array `tau`. From there, you can process the DRT however you want, or export it for use in other software.

Justt FYI, I also have a newer package, [hybrid-drt](https://github.com/jdhuang-csm/hybrid-drt), that expands upon the functionality in `bayes-drt`. I'm doing more active development of new features there (but `bayes-drt` still works well for most purposes!).

**Comment by Raj007Patel** [comment]
Hey there, I am trying to use bayes_drt as well as bayes_drt2 but keep failing. stuck on MSVC error, to rectify this I am also using gcc or Mingw but still issue persists. then i tried bayes_drt2 and got error like "Ipython is not defined". for past 10 days I am trying to execute this. My professor is getting angry. Please help.

**Comment by jdhuang-csm** [comment]
> Hey there, I am trying to use bayes_drt as well as bayes_drt2 but keep failing. stuck on MSVC error, to rectify this I am also using gcc or Mingw but still issue persists. then i tried bayes_drt2 and got error like "Ipython is not defined". for past 10 days I am trying to execute this. My professor is getting angry. Please help.

Hi, I'm sorry that the installation isn't working. Can you open a new issue for this and include the full error messages, as well as environment information? I will do my best to help you figure it out. FYI - if you are simply looking for a DRT package and don't need to use `bayes-drt2` specifically, I would recommend my newer package [`hybrid-drt`](https://github.com/jdhuang-csm/hybrid-drt), which should be much simpler to install.
